### ISSUE TITLE
R vs Python behavior difference regarding execute on page load -- intended?

### ISSUE THREAD

**Issue by rpruim** [r-wasm/quarto-live#57]
When I create live-html documents with webr, the code does not run until I hit the run code button, and there is an indicator when webr is ready to go.

When I create live-html documents with pyodide, the code seems to execute immediately upon page load, and there is no indicator for when pyodide is ready to go.

Is this an intended difference?  What I'd really like is a way to control which behavior I get.  

* Often I want to allow students to edit scaffolded code before the code is executed.  
* Other times I have chunks that I would like to execute upon page load with the option to edit the code and re-run.  
* I can imagine a use case for a chunk that run and can't be re-run as well.

**Comment by georgestagg** [comment]
> Often I want to allow students to edit scaffolded code before the code is executed.
> Other times I have chunks that I would like to execute upon page load with the option to edit the code and re-run.

The default for "sandbox" editable code blocks (i.e. not an `exercise` with hints or solutions attached) is to execute automatically on page load. On the other hand, when an `exercise` is created, the code cell will not automatically execute on page load. It is likely that this default will change in the future so that **no** type of code cell will execute automatically by default.

In any case, the defaults can be overridden in the document YAML metadata by setting the `autorun` key for the WebAssembly engine you're using. For example, the following should cause code cells _not_ to execute on page load:

````
---
title: execution test
format:
  live-html:
    pyodide:
      cell-options:
        autorun: false
toc: true
---

```{pyodide}
123 + 456
```
````

Conversely, in this document the cell should automatically execute:

````
---
title: execution test
format:
  live-html:
    pyodide:
      cell-options:
        autorun: true
toc: true
---

```{pyodide}
123 + 456
```
````

Finally, in this document there should be a mixture of behaviours:

````
---
title: execution test
format: live-html
toc: true
---

```{pyodide}
#| autorun: true
123 + 456
```

```{pyodide}
#| autorun: false
789 + 1011
```
````


------

> I can imagine a use case for a chunk that run and can't be re-run as well.

Perhaps a read-only cell would suffice in this case?

````
---
title: execution test
format: live-html
toc: true
---

```{pyodide}
#| edit: false
foo = 123
bar = 456
```

```{pyodide}
#| autorun: false
foo + bar
```
````

**Comment by rpruim** [comment]
Thanks!

I'll have to give this a try, but it looks like exactly what I was looking for -- just didn't locate that YAML setting in the documentation.

**Comment by georgestagg** [comment]
Great! Let me know if you have any issues and we'll re-open the thread.
