### ISSUE TITLE
Variables in the grading environment are not visible from the grading algorithm (pyodide)

### ISSUE THREAD

**Issue by joelostblom** [r-wasm/quarto-live#63]
I would like to create a common setup cell for several exercises. It seems like `setup:` does not accept an array of exercise names currently. Maybe a code chunk with `setup:` but without an exercise name specified (or specified as `*`) could propagate the setup code to all exercise environments?

A workaround I have found is to specify `envir: 'global'` in the exercise cell. I was initially planning to use this together with a hidden setup cell, but I'm having issues with `echo` to hide the cell as per https://github.com/r-wasm/quarto-live/issues/62. If this is a good solution, maybe it can be added to the docs?

**Comment by joelostblom** [comment]
One issue with my workaround is that it does not seem to work with `#| check: true` cells. Are these hardcoded to always use an environment named according to the name of the exercise?

**Comment by georgestagg** [comment]
Hi, thanks for reporting this.

Your method is one way that is supposed to work. It's also supposed to support setting any string value for `envir`, and where the values match the environment should be shared (for e.g. 2 exercises with a shared environment, but not the global environment).

The problem is that there is a currently bug where the variables from the shared environment are not being fed through to the grading environment. I'm sorry about that. This kind of thing should happen less often we have a unit testing framework up and running in the repo. One the bug is resolved, your exercises should work.

For the moment, you'll likely need to duplicate your setup code in your `check: true` cells. I know that's not ideal and hopefully we'll get things back in working order soon.

---

When this works, the `check: true` and `setup: true` cells should not need `envir` to be specified. They will pick it up from the main exercise block they are linked to via the `exercise` option.

---

> It seems like `setup:` does not accept an array of exercise names currently

Correct, it does not, but I like the idea. We should definitely support that as an alternative way to share setup.

**Comment by joelostblom** [comment]
> The problem is that there is a currently bug where the variables from the shared environment are not being fed through to the grading environment. I'm sorry about that. This kind of thing should happen less often we have a unit testing framework up and running in the repo. One the bug is resolved, your exercises should work.
>
> For the moment, you'll likely need to duplicate your setup code in your check: true cells. I know that's not ideal and hopefully we'll get things back in working order soon.

Thanks for confirming how things should work. I will use this as a workaround for the time being.

**Comment by georgestagg** [comment]
This should work better as of 3e7d3109633ec6b97547940579cc5fa9a33d2807.

I've hopefully fixed the bug with passing variables from the shared environment to the grading environment, example:

<details>

````
```{pyodide}
#| setup: true
#| exercise: ex_1_py
foo = 123
```

```{pyodide}
#| envir: myenv
#| exercise: ex_1_py
n = foo
```

```{pyodide}
#| exercise: ex_1_py
#| check: true
feedback = None
if (n == foo):
  feedback = { "correct": True, "message": "Nice work!" }
else:
  feedback = { "correct": False, "message": "That's incorrect, sorry." }
feedback
```

```{pyodide}
#| envir: myenv
#| exercise: ex_2_py
foo
```
````

</details>


And have also set things up so that a list of exercises can be passed to a `setup:true` block:

<details>

````
```{webr}
#| setup: true
#| exercise:
#|   - ex_a1
#|   - ex_a2
var_xyz <- c(1, 3, 7, 9, 13, 15)
```

```{webr}
#| exercise: ex_a1
var_xyz * 2
```

```{webr}
#| exercise: ex_a2
var_xyz ** 2
```
````

</details>

**Comment by joelostblom** [comment]
Works like a charm, thanks for the quick fix!
