### ISSUE TITLE
Custom grading

### ISSUE THREAD

**Issue by aneesha** [r-wasm/quarto-live#66]
Can the custom grading be extended to call and API? Looking for a way to call and API that then calls an LLM to do more advanced grading. Use case -- Explain In English code understanding feedback via an LLM.

Also really excellent project!

**Comment by georgestagg** [comment]
With R this is not yet easily possible, because the curl & httr packages are not yet supported in webR.

When using Python, this should be possible using Pyodide's built in `pyodide.http` shim to make network requests: https://pyodide.org/en/stable/usage/api/python-api/http.html. However, be aware that making direct calls to an LLM will be tricky, because the API keys will be visible to anyone visiting the page. As you suggest, they should be gated around some other (preferably authenticated) API.

(Apologies for the slow reply)
